mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = []

# ---Group post views
urlpatterns += [
    path('', views.post_list, name='post_list'),
    path('cbvs', views.PostListCbvsView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag')
]

# ---Group Sent Email
urlpatterns += [
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

# ---Group feed and search
urlpatterns += [
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mainapp/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    # url(r'^polls/', include('polls.urls')),
    # url(r'^blog/', include('polls.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

mysite/blog/models/cms_integration.py
from django.db import models
from cms.models import CMSPlugin
from .mPost import Post


class BlogPluginModel(CMSPlugin):
    blog = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.blog.title

mysite/blog/models/mComment.py
from django.db import models
# from django.utils import timezone
# from django.urls import reverse # get_absolute_url
# from django.contrib.auth.models import User

class Comment(models.Model):
    """NOTE_START 
    It contains ForeignKey to associate the
    comment with a single post. This many-to-one relationship is
    defined in the Comment model because each comment will be made on
    one post, and each post may have multiple comments.
    NOTE_END""" 
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

mysite/blog/models/mPost.py
from django.db import models
from django.utils import timezone
from django.urls import reverse  # get_absolute_url
from django.contrib.auth.models import User
# ---Group 3rd-party apps
from taggit.managers import TaggableManager

"""NOTE_START 
There are two ways to add managers to your models: you can add extra manager methods 
or modify initial manager QuerySets. The first method provides you with a QuerySet API 
suchas Post.objects.my_manager(), and the latter provides you with Post.my_manager.all() . 
The manager will allow us to retrieve posts using Post.published.all() 
NOTE_END"""


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(
            PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    """NOTE_START 
     objects is the default manager of every model that retrieves all objects in the database. 
     However, we can also define custom managers for our models. 
    NOTE_END"""
    # ---Group ObjectManager
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    """NOTE_START  Canonical URLs for models
    You can use the post_detail URL that you have defined in the preceding section to build 
    the canonical URL for Post objects. The convention in Django is to add a get_absolute_url() method 
    to the model that returns the canonical URL of the object. For this method, we will use 
    the reverse() method that allows you to build URLs by their name and passing optional parameters.
    NOTE_END"""

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

mysite/blog/forms/fComment.py
from django import forms
from blog.models import Comment

"""NOTE_START 
Remember that Django has two base classes to build forms, Form and ModelForm
To create a form from a model, we will just need to indicate which
model to use to build the form in the Meta class of the form. Django
introspects the model and builds the form dynamically for us. Each
model field type has a corresponding default form field type.. 
NOTE_END""" 
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/forms/fEmailPost.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
    widget=forms.Textarea)

mysite/blog/forms/fSearch.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views/vPost.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.db.models import Count
from blog.models import (Post, Comment)
from blog.forms import (EmailPostForm, CommentForm)
# ---Group paginator
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
# ---Group Class Base Views
from django.views.generic import ListView
# ---Group Email
from django.core.mail import send_mail
# ---Group 3rd-party app/module
from taggit.models import Tag


def post_list(request, tag_slug=None):
    # posts = Post.published.all()
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    # We get the page GET parameter that indicates the current page number.
    page = request.GET.get('page')

    # ---Group try exept
    try:
        # We obtain the objects for the desired page calling the page() method of Paginator
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


"""NOTE_START
kalo def post_list(request) di robah ke class base
NOTE_END"""


class PostListCbvsView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/listcbvs.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post, slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day)
    # ---Group List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ---Group  send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) recommends you reading "{}"'\
                .format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'\
                .format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})

mysite/blog/views/vSearch.py
from django.shortcuts import render
from django.contrib.postgres.search import (
    SearchVector,  SearchQuery, SearchRank, TrigramSimilarity)
from blog.models import Post
from blog.forms import SearchForm


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(search=search_vector, rank=SearchRank(
                search_vector, search_query))\
                .filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})


"""NOTE_START 
# ---Group Building a search view
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                search=SearchVector('title', 'body'))\
                .filter(search=query)
    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})
NOTE_END"""

"""NOTE_START 
# ---Group Stemming and ranking results
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(search=search_vector, rank=SearchRank(
                search_vector, search_query))\
                .filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})
NOTE_END"""

"""NOTE_START 
# ---Group Weighting queries
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_vector =\
                SearchVector('title', weight='A') + \
                SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})
NOTE_END""" 

"""NOTE_START  
# ---Group TrigramSimilarity
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_vector =\
                SearchVector('title', weight='A') + \
                SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})
NOTE_END"""

mysite/blog/templates/blog/post/_comment copy.html
<!-- Total Comment count -->
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

<!-- Comment Body -->
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}

<!-- Commet form -->
{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}

mysite/blog/templates/blog/post/_comment.html
<!-- Total Comment count -->
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

<!-- Comment Body -->
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}

<!-- Commet form -->
{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{% comment "NOTE_" %} -----
{{ post.body|linebreaks }}
----- {% endcomment %}
{{ post.body|markdown }}
<p>
    <a href="{% url "blog:post_share" post.id %}">
        Share this post
    </a>
</p>

<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}


{% include "./_comment.html" with page=posts %}

{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}s
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}

<h1>My Blog</h1>

{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

<!-- Loop for post -->
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
    <!-- Taggit -->
    <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>


<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}

<!-- PAGINATOR -->
{% include "../pagination.html" with page=posts %}

{% endblock %}

mysite/blog/templates/blog/post/listcbvs.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}

<h1>My Blog</h1>
<!-- Loop for post -->
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}

<!-- PAGINATOR -->
{% comment "NOTE_" %} -----
In order to keep pagination working, we have to use the right page
object that is passed to the template. Django's ListView generic view
passes the selected page in a variable called page_obj , so you have to
edit your post/list.html template accordingly to include the paginator
using the right variable, as follows:
    change 
    {% include "pagination.html" with page=page %}
    to 
    {% include "pagination.html" with page=page_obj %}
----- {% endcomment %}


{% include "pagination.html" with page=page_obj %}

{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url "blog:post_search" %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form action="." method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

<!-- title  -->
{% block title %}
Share a post
{% endblock %}

<!-- konten -->
{% block content %}

{% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
{% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
</form>
{% endif %}

{% endblock %}